version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: freierfrei23-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    depends_on:
      - backend
      - frontend
    restart: always

  backend:
    build: ./backend
    container_name: freierfrei23-backend
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,backend
    restart: always
    command: >
      bash -c "python manage.py collectstatic --noinput && 
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    container_name: freierfrei23-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    expose:
      - 3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api
    restart: always
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume: